@baseUrl = http://[::1]:3333
@AuthToken = {{autenticate.response.body.acess_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Iuri Reis",
    "email": "iuri@rei7.com",
    "password": "123456"
}

###

# @name autenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "iuri@rei.com",
    "password": "123456"
}

###

# @name create-question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
    "title": "Nova Pergunta",
    "content": "essa é a nova pergunta"
}