@baseUrl = http://[::1]:3333
@AuthToken = {{autenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Iuri Reis",
    "email": "iuri@rei.com",
    "password": "123456"
}

###

# @name autenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "iuri@rei7.com",
    "password": "123456"
}

###

# @name create-question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
    "title": "Nova Pergunta9",
    "content": "essa é a nova pergunta"
}

###

# @name fetch-recent-questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

###

# @name upload-attachments
POST {{baseUrl}}/attachments
Content-Type: multipart/form-data
Authorization: Bearer {{AuthToken}}
< ./test/E2E/sample-upload.pdf
